import type { CityConfig } from './types';

export const CHENNAI: CityConfig = {
  cityId: 'chennai',
  displayName: 'Chennai',
  stateCode: 'TN',
  timezone: 'Asia/Kolkata',
  center: { lat: 13.0827, lng: 80.2707 },
  bbox: { south: 12.7, north: 13.4, west: 79.9, east: 80.4 },
  primaryAuthority: {
    code: 'cmwssb',
    name: 'Chennai Metropolitan Water Supply and Sewerage Board',
    acronym: 'CMWSSB',
  },
  localGovernment: {
    code: 'gcc',
    name: 'Greater Chennai Corporation',
    acronym: 'GCC',
    wardCount: 200,
  },
  defaultConsumptionMld: 830,
  defaultDesalinationMld: 190,
  waterSources: [
    {
      sourceCode: 'chembarambakkam',
      displayName: 'Chembarambakkam',
      type: 'reservoir',
      fullCapacityMcft: 3645.0,
      fullTankLevelFt: 24.0,
      latitude: 12.9517,
      longitude: 80.0551,
      catchmentAreaSqkm: 71.6,
      displayOrder: 1,
      isPrimaryDrinkingSource: true,
    },
    {
      sourceCode: 'redhills',
      displayName: 'Red Hills (Puzhal)',
      type: 'reservoir',
      fullCapacityMcft: 3300.0,
      fullTankLevelFt: 48.5,
      latitude: 13.171,
      longitude: 80.1811,
      catchmentAreaSqkm: 60.3,
      displayOrder: 2,
      isPrimaryDrinkingSource: true,
    },
    {
      sourceCode: 'poondi',
      displayName: 'Poondi',
      type: 'reservoir',
      fullCapacityMcft: 3231.0,
      fullTankLevelFt: 36.0,
      latitude: 13.3542,
      longitude: 80.0678,
      catchmentAreaSqkm: 2530.0,
      displayOrder: 3,
      isPrimaryDrinkingSource: true,
    },
    {
      sourceCode: 'veeranam',
      displayName: 'Veeranam',
      type: 'reservoir',
      fullCapacityMcft: 1465.0,
      fullTankLevelFt: null,
      latitude: 11.35,
      longitude: 79.54,
      catchmentAreaSqkm: null,
      displayOrder: 4,
      isPrimaryDrinkingSource: false,
    },
    {
      sourceCode: 'kannankottai',
      displayName: 'Kannankottai (TK)',
      type: 'reservoir',
      fullCapacityMcft: 500.0,
      fullTankLevelFt: null,
      latitude: 12.82,
      longitude: 79.98,
      catchmentAreaSqkm: null,
      displayOrder: 5,
      isPrimaryDrinkingSource: false,
    },
    {
      sourceCode: 'cholavaram',
      displayName: 'Cholavaram',
      type: 'reservoir',
      fullCapacityMcft: 1081.0,
      fullTankLevelFt: 22.0,
      latitude: 13.2184,
      longitude: 80.1499,
      catchmentAreaSqkm: 77.4,
      displayOrder: 6,
      isPrimaryDrinkingSource: true,
    },
  ],
  sourceNameAliases: {
    poondi: 'poondi',
    cholavaram: 'cholavaram',
    puzhal: 'redhills',
    'red hills': 'redhills',
    chembarambakkam: 'chembarambakkam',
    veeranam: 'veeranam',
    kannankottai: 'kannankottai',
    'thervoy kandigai': 'kannankottai',
  },
};
