import type { RegionConfig } from './types';

export const KAVERI: RegionConfig = {
  placeKind: 'region',
  cityId: 'kaveri',
  displayName: 'Kaveri Delta',
  stateCode: 'TN',
  timezone: 'Asia/Kolkata',
  // Hidden from CitySwitcher dropdown + sitemap while requirements are
  // being signed off. /cauvery URL stays alive so anyone with a direct
  // link can still reach the in-progress page; only nav discovery is
  // suppressed.
  hiddenFromDiscovery: true,
  center: { lat: 10.78, lng: 79.13 },
  bbox: { south: 10.0, north: 13.0, west: 77.0, east: 80.0 },
  primaryAuthority: {
    code: 'tn_wrd',
    name: 'Tamil Nadu Water Resources Department',
    acronym: 'TN WRD',
  },
  defaultConsumptionMld: null,
  defaultDesalinationMld: null,
  waterSources: [
    {
      sourceCode: 'mettur',
      displayName: 'Mettur',
      type: 'reservoir',
      fullCapacityMcft: 93400.0,
      fullTankLevelFt: 120.0,
      latitude: 11.7888,
      longitude: 77.7917,
      catchmentAreaSqkm: 42200.0,
      displayOrder: 1,
      isPrimaryDrinkingSource: false,
    },
    {
      sourceCode: 'krs',
      displayName: 'Krishna Raja Sagara (KRS)',
      type: 'reservoir',
      fullCapacityMcft: 49450.0,
      fullTankLevelFt: null,
      latitude: 12.4242,
      longitude: 76.5717,
      catchmentAreaSqkm: 10619.0,
      displayOrder: 2,
      isPrimaryDrinkingSource: false,
    },
    {
      sourceCode: 'kabini',
      displayName: 'Kabini',
      type: 'reservoir',
      fullCapacityMcft: 19520.0,
      fullTankLevelFt: null,
      latitude: 11.9706,
      longitude: 76.35,
      catchmentAreaSqkm: 2141.0,
      displayOrder: 3,
      isPrimaryDrinkingSource: false,
    },
    {
      sourceCode: 'hemavathy',
      displayName: 'Hemavathy',
      type: 'reservoir',
      fullCapacityMcft: 37100.0,
      fullTankLevelFt: null,
      latitude: 12.8167,
      longitude: 76.05,
      catchmentAreaSqkm: 2810.0,
      displayOrder: 4,
      isPrimaryDrinkingSource: false,
    },
    {
      sourceCode: 'harangi',
      displayName: 'Harangi',
      type: 'reservoir',
      fullCapacityMcft: 8500.0,
      fullTankLevelFt: null,
      latitude: 12.4972,
      longitude: 75.9069,
      catchmentAreaSqkm: 419.0,
      displayOrder: 5,
      isPrimaryDrinkingSource: false,
    },
    {
      sourceCode: 'biligundlu',
      displayName: 'Biligundlu (CWMA control)',
      type: 'flow_station',
      fullCapacityMcft: null,
      fullTankLevelFt: null,
      latitude: 12.05,
      longitude: 77.6,
      catchmentAreaSqkm: null,
      displayOrder: 6,
      isPrimaryDrinkingSource: false,
    },
  ],
  sourceNameAliases: {
    mettur: 'mettur',
    'mettur dam': 'mettur',
    krs: 'krs',
    'krishna raja sagara': 'krs',
    krishnarajasagara: 'krs',
    kabini: 'kabini',
    hemavathy: 'hemavathy',
    'hemavathi': 'hemavathy',
    harangi: 'harangi',
    biligundlu: 'biligundlu',
  },
};
