import type { CityConfig } from './types';

export const MADURAI: CityConfig = {
  placeKind: 'city',
  cityId: 'madurai',
  displayName: 'Madurai',
  stateCode: 'TN',
  timezone: 'Asia/Kolkata',
  center: { lat: 9.9252, lng: 78.1198 },
  bbox: { south: 9.85, north: 10.0, west: 78.05, east: 78.2 },
  primaryAuthority: {
    code: 'mmc',
    name: 'Madurai Municipal Corporation',
    acronym: 'MMC',
  },
  localGovernment: {
    code: 'mmc',
    name: 'Madurai Municipal Corporation',
    acronym: 'MMC',
    wardCount: 100,
  },
  defaultConsumptionMld: 135,
  defaultDesalinationMld: null,
  waterSources: [
    {
      sourceCode: 'vaigai',
      displayName: 'Vaigai Dam',
      type: 'reservoir',
      fullCapacityMcft: 6837.0,
      fullTankLevelFt: 71.0,
      latitude: 10.0533,
      longitude: 77.5897,
      catchmentAreaSqkm: 2253.0,
      displayOrder: 1,
      isPrimaryDrinkingSource: true,
    },
    {
      sourceCode: 'mullaperiyar',
      displayName: 'Mullaperiyar (Periyar) Dam',
      type: 'reservoir',
      // SC 2014 verdict caps Kerala-side storage at 142 ft; the historical
      // 152 ft TN FRL (~15,660 mcft) is no longer operationally available.
      fullCapacityMcft: 10560.0,
      fullTankLevelFt: 142.0,
      latitude: 9.5394,
      longitude: 77.1422,
      catchmentAreaSqkm: 624.0,
      displayOrder: 2,
      isPrimaryDrinkingSource: true,
    },
    {
      sourceCode: 'sothuparai',
      displayName: 'Sothuparai Dam',
      type: 'reservoir',
      fullCapacityMcft: 1272.0,
      fullTankLevelFt: null,
      latitude: 10.07,
      longitude: 77.45,
      catchmentAreaSqkm: null,
      displayOrder: 3,
      isPrimaryDrinkingSource: false,
    },
  ],
  sourceNameAliases: {
    vaigai: 'vaigai',
    'vaigai dam': 'vaigai',
    'வைகை': 'vaigai',
    mullaperiyar: 'mullaperiyar',
    'mullai periyar': 'mullaperiyar',
    periyar: 'mullaperiyar',
    'periyar dam': 'mullaperiyar',
    'மூலைப்பெரியார்': 'mullaperiyar',
    sothuparai: 'sothuparai',
    'sothuparai dam': 'sothuparai',
    'சோத்துப்பாறை': 'sothuparai',
  },
};
