/** Bengaluru's daily-briefing copy (en/ta/kn). {placeholders} are filled from
 *  the briefing fields built in lib/insights/bangalore-briefing.ts. */
export const BRIEFING_COPY = {
  headline: {
    drought_drawdown: { en: "Cauvery basin in drought drawdown: 4 upstream dams at just {pct}% of FRL combined.", ta: "காவிரி தடாக்கம் வறட்சி இறக்கத்தில்: 4 மேற்பகுதி அணைகள் கூட்டாக {pct}% FRL-ல் மட்டுமே.", kn: "ಕಾವೇರಿ ಜಲಾನಯನ ಬರಗಾಲದ ಇಳಿತದಲ್ಲಿ: 4 ಮೇಲ್ಭಾಗದ ಅಣೆಕಟ್ಟುಗಳು ಒಟ್ಟಾಗಿ ಕೇವಲ {pct}% FRL ನಲ್ಲಿ." },
    pre_monsoon: { en: "Pre-monsoon drawdown: Cauvery upstream at {pct}% of FRL, awaiting south-west monsoon onset.", ta: "பருவமழைக்கு முந்தைய இறக்கம்: காவிரி மேற்பகுதி {pct}% FRL-ல், தென்மேற்கு பருவமழை வரத்துக்காக காத்திருக்கிறது.", kn: "ಮುಂಗಾರು-ಪೂರ್ವ ಇಳಿತ: ಕಾವೇರಿ ಮೇಲ್ಭಾಗ {pct}% FRL ನಲ್ಲಿ, ನೈರುತ್ಯ ಮುಂಗಾರು ಆಗಮನಕ್ಕಾಗಿ ಕಾಯುತ್ತಿದೆ." },
    monsoon_recharge: { en: "Cauvery basin in monsoon recharge: 4 upstream dams at {pct}% of FRL combined.", ta: "காவிரி தடாக்கம் பருவமழை நிரப்புதலில்: 4 மேற்பகுதி அணைகள் கூட்டாக {pct}% FRL.", kn: "ಕಾವೇರಿ ಜಲಾನಯನ ಮುಂಗಾರು ಮರುಪೂರಣದಲ್ಲಿ: 4 ಮೇಲ್ಭಾಗದ ಅಣೆಕಟ್ಟುಗಳು ಒಟ್ಟಾಗಿ {pct}% FRL ನಲ್ಲಿ." },
    post_monsoon: { en: "Cauvery basin near full storage: 4 upstream dams at {pct}% of FRL combined.", ta: "காவிரி தடாக்கம் முழுச் சேமிப்புக்கு அருகில்: 4 மேற்பகுதி அணைகள் கூட்டாக {pct}% FRL.", kn: "ಕಾವೇರಿ ಜಲಾನಯನ ಪೂರ್ಣ ಸಂಗ್ರಹಕ್ಕೆ ಸಮೀಪ: 4 ಮೇಲ್ಭಾಗದ ಅಣೆಕಟ್ಟುಗಳು ಒಟ್ಟಾಗಿ {pct}% FRL ನಲ್ಲಿ." },
    steady_drawdown: { en: "Cauvery upstream storage at {pct}% of FRL - mid-cycle draw against next monsoon.", ta: "காவிரி மேற்பகுதி சேமிப்பு {pct}% FRL-ல் - அடுத்த பருவமழைக்கு எதிராக நடுவில் இறக்கம்.", kn: "ಕಾವೇರಿ ಮೇಲ್ಭಾಗ ಸಂಗ್ರಹ {pct}% FRL ನಲ್ಲಿ - ಮುಂದಿನ ಮುಂಗಾರಿಗೆ ಎದುರಾಗಿ ಮಧ್ಯ-ಚಕ್ರ ಇಳಿತ." },
  },
  sentence: {
    dam_range: { en: "{lowName} is the most-drawn at {lowPct}% FRL; {highName} carries the most buffer at {highPct}% FRL.", ta: "{lowName} {lowPct}% FRL-ல் அதிகம் இறக்கப்பட்டது; {highName} {highPct}% FRL-ல் அதிக காப்பு கொண்டுள்ளது.", kn: "{lowName} {lowPct}% FRL ನಲ್ಲಿ ಅತಿ ಹೆಚ್ಚು ಎತ್ತಲಾಗಿದೆ; {highName} {highPct}% FRL ನಲ್ಲಿ ಅತಿ ಹೆಚ್ಚು ಬಫರ್ ಹೊಂದಿದೆ." },
    stage_v: { en: "BWSSB's Cauvery Stage V (commissioned 16 Oct 2024) is delivering only ~{actual} of {design} MLD design as of Feb 2026 (The Ken). Fully delivered, post-Stage-V supply covers the 2034 demand (~2,608 MLD) but still falls ~721 MLD short by 2049.", ta: "BWSSB-ன் காவிரி நிலை V (அக் 2024-ல் தொடங்கப்பட்டது) ~{actual} MLD-ஐ {design} MLD வடிவமைப்புக்கு எதிராக வழங்குகிறது (The Ken, பிப் 2026), நகரத்தின் குழாய் திறனை முழு மேற்பகுதி சேமிப்பிலும் 2034 தேவைக்குக் கீழே வைத்திருக்கிறது.", kn: "BWSSB ಯ ಕಾವೇರಿ Stage V (16 ಅಕ್ಟೋಬರ್ 2024 ರಂದು ಚಾಲನೆಗೊಂಡಿತು) ಫೆಬ್ 2026 ರ ಪ್ರಕಾರ {design} MLD ವಿನ್ಯಾಸದಲ್ಲಿ ಕೇವಲ ~{actual} MLD ತಲುಪಿಸುತ್ತಿದೆ (The Ken). ಪೂರ್ಣ ತಲುಪಿಸಿದರೆ, Stage V ನಂತರದ ಪೂರೈಕೆ 2034 ಬೇಡಿಕೆಯನ್ನು (~2,608 MLD) ಪೂರೈಸುತ್ತದೆ ಆದರೆ 2049 ರ ವೇಳೆಗೆ ~721 MLD ಕೊರತೆ ಉಳಿಯುತ್ತದೆ." },
    demand_side: { en: "~{served}M residents fall within BWSSB's piped jurisdiction, but actual coverage is only ~71% (ISEC, 2017-18); the rest depend on over-extracted borewells and the ~{tankers}-tanker informal market. IISc Groundwater Outlook (Apr 2025) flags {wards} BBMP wards as critically over-extracted.", ta: "{gba}M GBA குடியிருப்பாளர்களில் ~{served}M BWSSB குழாய் வழங்கலில் உள்ளனர்; மீதமுள்ளவர்கள் அதிகமாக எடுக்கப்படும் ஆழ்துளைக் கிணறுகள் மற்றும் ~{tankers} டேங்கர் சந்தையைச் சார்ந்துள்ளனர். IISc நிலத்தடி நீர் கண்காணிப்பு (ஏப் 2025) {wards} BBMP வார்டுகளை மிகவும் அதிகமாக எடுக்கப்பட்டவையாக அடையாளம் காட்டுகிறது.", kn: "~{served}M ನಿವಾಸಿಗಳು BWSSB ಯ ಪೈಪ್ ವ್ಯಾಪ್ತಿಯೊಳಗೆ ಬರುತ್ತಾರೆ, ಆದರೆ ವಾಸ್ತವಿಕ ಕವರೇಜ್ ಕೇವಲ ~71% (ISEC, 2017-18); ಉಳಿದವರು ಅತಿಯಾಗಿ ಎತ್ತಲ್ಪಟ್ಟ ಬೋರ್‌ವೆಲ್‌ಗಳು ಮತ್ತು ~{tankers} ಟ್ಯಾಂಕರ್ ಅನೌಪಚಾರಿಕ ಮಾರುಕಟ್ಟೆಯನ್ನು ಅವಲಂಬಿಸಿದ್ದಾರೆ. IISc ಅಂತರ್ಜಲ ಔಟ್‌ಲುಕ್ (ಏಪ್ರಿಲ್ 2025) {wards} BBMP ವಾರ್ಡ್‌ಗಳನ್ನು ಗಂಭೀರವಾಗಿ ಅತಿ-ಎತ್ತಲ್ಪಟ್ಟ ಎಂದು ಗುರುತಿಸಿದೆ." },
    tail: {
      drought_drawdown: { en: "At this drawdown level, Karnataka's drinking-water carve-out at T.K. Halli is the first item under pressure - irrigation releases get curtailed before urban supply, but pumping itself becomes more contested. Watch the Cauvery Water Management Authority release schedules.", ta: "இந்த இறக்க அளவில், டி.கே. ஹல்லியில் கர்நாடகாவின் குடிநீர் ஒதுக்கீடு முதலில் அழுத்தத்தில் வரும் - நகர வழங்கலுக்கு முன் பாசன வெளியீடுகள் குறைக்கப்படும், ஆனால் பம்பிங் தானே போட்டியில் வரும். காவிரி நீர் மேலாண்மை ஆணையத்தின் வெளியீட்டு அட்டவணைகளைக் கவனியுங்கள்.", kn: "ಈ ಇಳಿತ ಮಟ್ಟದಲ್ಲಿ, T.K. ಹಳ್ಳಿಯಲ್ಲಿ ಕರ್ನಾಟಕದ ಕುಡಿಯುವ ನೀರಿನ ಪಾಲು ಮೊದಲ ಒತ್ತಡದ ಐಟಂ - ನಗರ ಪೂರೈಕೆಗೆ ಮುಂಚೆ ನೀರಾವರಿ ಬಿಡುಗಡೆಗಳು ಕಡಿಮೆಯಾಗುತ್ತವೆ, ಆದರೆ ಪಂಪಿಂಗ್ ಸ್ವತಃ ಹೆಚ್ಚು ಸ್ಪರ್ಧಾತ್ಮಕವಾಗುತ್ತದೆ. ಕಾವೇರಿ ನೀರು ನಿರ್ವಹಣಾ ಪ್ರಾಧಿಕಾರದ ಬಿಡುಗಡೆ ವೇಳಾಪಟ್ಟಿಗಳನ್ನು ಗಮನಿಸಿ." },
      pre_monsoon: { en: "Monsoon onset for the Cauvery catchment is typically the first week of June (south-west monsoon). KRS + Hemavathi typically refill 60-80% by end-July in a normal year; weak monsoons (2017, 2023) push that into August.", ta: "காவிரி வடிநிலத்திற்கான பருவமழை வரத்து பொதுவாக ஜூன் முதல் வாரம் (தென்மேற்கு பருவமழை). KRS + ஹேமாவதி பொதுவாக ஜூலை முடிவில் 60-80% நிரம்பும் ஒரு சாதாரண ஆண்டில்; பலவீன பருவமழைகள் (2017, 2023) அதை ஆகஸ்ட்டுக்கு தள்ளும்.", kn: "ಕಾವೇರಿ ಜಲಾನಯನಕ್ಕೆ ಮುಂಗಾರು ಆಗಮನ ಸಾಮಾನ್ಯವಾಗಿ ಜೂನ್‌ನ ಮೊದಲ ವಾರ (ನೈರುತ್ಯ ಮುಂಗಾರು). KRS + ಹೇಮಾವತಿ ಸಾಮಾನ್ಯ ವರ್ಷದಲ್ಲಿ ಜುಲೈ ಅಂತ್ಯದ ವೇಳೆಗೆ 60-80% ಮರುಭರ್ತಿಯಾಗುತ್ತವೆ; ದುರ್ಬಲ ಮುಂಗಾರುಗಳು (2017, 2023) ಅದನ್ನು ಆಗಸ್ಟ್‌ಗೆ ತಳ್ಳುತ್ತವೆ." },
      monsoon_recharge: { en: "Recharge season also coincides with the BBMP foam-fire window - Bellandur's downstream weir typically produces surfactant foam events in the first heavy rains after a dry stretch (Feb 2017 fire was the canonical event).", ta: "நிரப்புதல் காலம் BBMP நுரை-தீ சாளரத்துடன் ஒத்துவருகிறது - பெல்லந்தூரின் கீழ்நிலை வீர் பொதுவாக ஒரு வறட்சி நீட்டிப்புக்குப் பிறகான முதல் கனமழைகளில் சர்பேக்டெண்ட் நுரை நிகழ்வுகளை உருவாக்கும் (பிப் 2017 தீ சாதாரண நிகழ்வாக இருந்தது).", kn: "ಮರುಪೂರಣ ಋತು BBMP ಫೋಮ್-ಬೆಂಕಿ ಅವಧಿಯೊಂದಿಗೆ ಸಹ ಹೊಂದಾಣಿಕೆಯಾಗುತ್ತದೆ - ಬೆಲ್ಲಂದೂರ್‌ನ ಕೆಳಭಾಗದ ಒಡ್ಡು ಸಾಮಾನ್ಯವಾಗಿ ಒಂದು ಒಣ ವಿಸ್ತಾರದ ನಂತರ ಮೊದಲ ಭಾರೀ ಮಳೆಯಲ್ಲಿ ಸರ್ಫ್ಯಾಕ್ಟಂಟ್ ಫೋಮ್ ಘಟನೆಗಳನ್ನು ಉಂಟುಮಾಡುತ್ತದೆ (ಫೆಬ್ 2017 ಬೆಂಕಿ ಪ್ರಾಮಾಣಿಕ ಘಟನೆಯಾಗಿತ್ತು)." },
      post_monsoon: { en: "Even at full upstream storage, BWSSB's ~{nrw}% non-revenue water (audited 2017-18, ISEC) means more than a third of what's pumped 95 km from T.K. Halli is lost between WTP and household meter. BWSSB reports a further reduction toward ~30%, not yet independently audited.", ta: "முழு மேற்பகுதி சேமிப்பிலும், BWSSB-ன் ~{nrw}% வருவாய் இல்லாத நீர் (JICA கட்டம் 3) என்பது டி.கே. ஹல்லியில் இருந்து 95 கி.மீ பம்ப் செய்யப்படுவதில் கிட்டத்தட்ட பாதி WTP மற்றும் வீட்டு மீட்டருக்கு இடையில் இழக்கப்படுகிறது என்பதாகும்.", kn: "ಪೂರ್ಣ ಮೇಲ್ಭಾಗ ಸಂಗ್ರಹದಲ್ಲೂ, BWSSB ಯ ~{nrw}% ಆದಾಯವಲ್ಲದ ನೀರು (2017-18 ಲೆಕ್ಕಪರಿಶೋಧಿತ, ISEC) ಎಂದರೆ T.K. ಹಳ್ಳಿಯಿಂದ 95 ಕಿಮೀ ಪಂಪ್ ಮಾಡಿದ್ದರಲ್ಲಿ ಮೂರನೇ ಒಂದಕ್ಕಿಂತ ಹೆಚ್ಚು WTP ಮತ್ತು ಮನೆಯ ಮೀಟರ್ ನಡುವೆ ಕಳೆದುಹೋಗುತ್ತದೆ. BWSSB ~30% ಕಡೆಗೆ ಮತ್ತಷ್ಟು ಕಡಿತವನ್ನು ವರದಿ ಮಾಡುತ್ತದೆ, ಇನ್ನೂ ಸ್ವತಂತ್ರವಾಗಿ ಲೆಕ್ಕಪರಿಶೋಧಿಸಲಾಗಿಲ್ಲ." },
      steady_drawdown: { en: "Mid-cycle drawdown phase. Each percentage point of FRL on these four dams represents roughly {tmcPerPct} TMC of basin storage - the same volume Bengaluru's piped network distributes in about 25 days at current pumping rates.", ta: "நடுவில் இறக்க கட்டம். இந்த நான்கு அணைகளில் FRL-ன் ஒவ்வொரு சதவீத புள்ளியும் சுமார் {tmcPerPct} TMC தடாக சேமிப்பைக் குறிக்கிறது - இது தற்போதைய பம்பிங் விகிதங்களில் பெங்களூரின் குழாய் வலையமைப்பு சுமார் 25 நாட்களில் விநியோகிக்கும் அதே அளவாகும்.", kn: "ಮಧ್ಯ-ಚಕ್ರ ಇಳಿತ ಹಂತ. ಈ ನಾಲ್ಕು ಅಣೆಕಟ್ಟುಗಳಲ್ಲಿ FRL ನ ಪ್ರತಿ ಶೇಕಡಾ ಬಿಂದು ಸುಮಾರು {tmcPerPct} TMC ಜಲಾನಯನ ಸಂಗ್ರಹವನ್ನು ಪ್ರತಿನಿಧಿಸುತ್ತದೆ - ಪ್ರಸ್ತುತ ಪಂಪಿಂಗ್ ದರಗಳಲ್ಲಿ ಬೆಂಗಳೂರಿನ ಪೈಪ್ ಜಾಲ ಸುಮಾರು 25 ದಿನಗಳಲ್ಲಿ ವಿತರಿಸುವ ಅದೇ ಪರಿಮಾಣ." },
    },
  },
  freshness: {
    with_date: { en: "Cauvery upstream storage: {date} - refreshed daily via Karnataka WRIS", ta: "காவிரி மேற்பகுதி சேமிப்பு: {date} - கர்நாடக WRIS வழியாக தினசரி புதுப்பிக்கப்பட்டது", kn: "ಕಾವೇರಿ ಮೇಲ್ಭಾಗ ಸಂಗ್ರಹ: {date} - ಕರ್ನಾಟಕ WRIS ಮೂಲಕ ದಿನಂಪ್ರತಿ ರಿಫ್ರೆಶ್" },
    pending: { en: "Cauvery upstream storage: live ingest pending", ta: "காவிரி மேற்பகுதி சேமிப்பு: நேரடி உள்ளீடு நிலுவையில்", kn: "ಕಾವೇರಿ ಮೇಲ್ಭಾಗ ಸಂಗ್ರಹ: ನೇರ ಪ್ರವೇಶ ಬಾಕಿ" },
  },
  heading: { en: "Today's briefing", ta: "இன்றைய சுருக்கம்", kn: "ಇಂದಿನ ಸಂಕ್ಷಿಪ್ತ" },
  variant: {
    drought_drawdown: { en: "Drought drawdown", ta: "வறட்சி குறைவு", kn: "ಬರಗಾಲದ ಇಳಿತ" },
    pre_monsoon: { en: "Pre-monsoon", ta: "பருவமழைக்கு முன்", kn: "ಮುಂಗಾರು-ಪೂರ್ವ" },
    monsoon_recharge: { en: "Monsoon recharge", ta: "பருவமழை நிரப்புதல்", kn: "ಮುಂಗಾರು ಮರುಪೂರಣ" },
    post_monsoon: { en: "Post-monsoon plateau", ta: "பருவமழைக்குப் பிறகு", kn: "ಮುಂಗಾರು-ಉತ್ತರ ಸ್ಥಿರತೆ" },
    steady_drawdown: { en: "Steady drawdown", ta: "நிலையான குறைவு", kn: "ಸ್ಥಿರ ಇಳಿತ" },
  },
  link_groundwater: { en: "Groundwater (blocks + risk)", ta: "நிலத்தடி நீர் (தொகுதிகள் + ஆபத்து)", kn: "ಅಂತರ್ಜಲ (ಬ್ಲಾಕ್‌ಗಳು + ಅಪಾಯ)" },
  link_tanker: "nav.tanker",
  link_lakes: { en: "Lakes + cascade", ta: "ஏரிகள் + அடுக்கு", kn: "ಕೆರೆಗಳು + ಸರಪಳಿ" },
  cauvery_storage_label: { en: "Cauvery upstream storage", ta: "காவிரி மேற்பகுதி சேமிப்பு", kn: "ಕಾವೇರಿ ಮೇಲ್ಭಾಗ ಸಂಗ್ರಹ" },
};
