from .types import (
    Authority,
    CityConfig,
    Coordinates,
    GeoBounds,
    LocalGovernment,
    WaterSourceConfig,
)

CHENNAI = CityConfig(
    place_kind="city",
    city_id="chennai",
    display_name="Chennai",
    state_code="TN",
    timezone="Asia/Kolkata",
    center=Coordinates(lat=13.0827, lng=80.2707),
    bbox=GeoBounds(south=12.7, north=13.4, west=79.9, east=80.4),
    primary_authority=Authority(
        code="cmwssb",
        name="Chennai Metropolitan Water Supply and Sewerage Board",
        acronym="CMWSSB",
    ),
    local_government=LocalGovernment(
        code="gcc",
        name="Greater Chennai Corporation",
        acronym="GCC",
        ward_count=200,
    ),
    default_consumption_mld=830.0,
    default_desalination_mld=190.0,
    water_sources=(
        WaterSourceConfig(
            source_code="chembarambakkam",
            display_name="Chembarambakkam",
            source_type="reservoir",
            full_capacity_mcft=3645.0,
            full_tank_level_ft=24.0,
            latitude=12.9517,
            longitude=80.0551,
            catchment_area_sqkm=71.6,
            display_order=1,
            is_primary_drinking_source=True,
        ),
        WaterSourceConfig(
            source_code="redhills",
            display_name="Red Hills (Puzhal)",
            source_type="reservoir",
            full_capacity_mcft=3300.0,
            full_tank_level_ft=48.5,
            latitude=13.171,
            longitude=80.1811,
            catchment_area_sqkm=60.3,
            display_order=2,
            is_primary_drinking_source=True,
        ),
        WaterSourceConfig(
            source_code="poondi",
            display_name="Poondi",
            source_type="reservoir",
            full_capacity_mcft=3231.0,
            full_tank_level_ft=36.0,
            latitude=13.3542,
            longitude=80.0678,
            catchment_area_sqkm=2530.0,
            display_order=3,
            is_primary_drinking_source=True,
        ),
        WaterSourceConfig(
            source_code="veeranam",
            display_name="Veeranam",
            source_type="reservoir",
            full_capacity_mcft=1465.0,
            full_tank_level_ft=None,
            latitude=11.35,
            longitude=79.54,
            catchment_area_sqkm=None,
            display_order=4,
            is_primary_drinking_source=False,
        ),
        WaterSourceConfig(
            source_code="kannankottai",
            display_name="Kannankottai (TK)",
            source_type="reservoir",
            full_capacity_mcft=500.0,
            full_tank_level_ft=None,
            latitude=12.82,
            longitude=79.98,
            catchment_area_sqkm=None,
            display_order=5,
            is_primary_drinking_source=False,
        ),
        WaterSourceConfig(
            source_code="cholavaram",
            display_name="Cholavaram",
            source_type="reservoir",
            full_capacity_mcft=1081.0,
            full_tank_level_ft=22.0,
            latitude=13.2184,
            longitude=80.1499,
            catchment_area_sqkm=77.4,
            display_order=6,
            is_primary_drinking_source=True,
        ),
    ),
    source_name_aliases={
        "poondi": "poondi",
        "cholavaram": "cholavaram",
        "puzhal": "redhills",
        "red hills": "redhills",
        "chembarambakkam": "chembarambakkam",
        "veeranam": "veeranam",
        "kannankottai": "kannankottai",
        "thervoy kandigai": "kannankottai",
    },
)
