from .types import (
    Authority,
    Coordinates,
    GeoBounds,
    RegionConfig,
    WaterSourceConfig,
)

KAVERI = RegionConfig(
    place_kind="region",
    city_id="kaveri",
    display_name="Kaveri Delta",
    state_code="TN",
    timezone="Asia/Kolkata",
    center=Coordinates(lat=10.78, lng=79.13),
    bbox=GeoBounds(south=10.0, north=13.0, west=77.0, east=80.0),
    primary_authority=Authority(
        code="tn_wrd",
        name="Tamil Nadu Water Resources Department",
        acronym="TN WRD",
    ),
    default_consumption_mld=None,
    default_desalination_mld=None,
    water_sources=(
        WaterSourceConfig(
            source_code="mettur",
            display_name="Mettur",
            source_type="reservoir",
            full_capacity_mcft=93400.0,
            full_tank_level_ft=120.0,
            latitude=11.7888,
            longitude=77.7917,
            catchment_area_sqkm=42200.0,
            display_order=1,
            is_primary_drinking_source=False,
        ),
        WaterSourceConfig(
            source_code="krs",
            display_name="Krishna Raja Sagara (KRS)",
            source_type="reservoir",
            full_capacity_mcft=49450.0,
            full_tank_level_ft=None,
            latitude=12.4242,
            longitude=76.5717,
            catchment_area_sqkm=10619.0,
            display_order=2,
            is_primary_drinking_source=False,
        ),
        WaterSourceConfig(
            source_code="kabini",
            display_name="Kabini",
            source_type="reservoir",
            full_capacity_mcft=19520.0,
            full_tank_level_ft=None,
            latitude=11.9706,
            longitude=76.35,
            catchment_area_sqkm=2141.0,
            display_order=3,
            is_primary_drinking_source=False,
        ),
        WaterSourceConfig(
            source_code="hemavathy",
            display_name="Hemavathy",
            source_type="reservoir",
            full_capacity_mcft=37100.0,
            full_tank_level_ft=None,
            latitude=12.8167,
            longitude=76.05,
            catchment_area_sqkm=2810.0,
            display_order=4,
            is_primary_drinking_source=False,
        ),
        WaterSourceConfig(
            source_code="harangi",
            display_name="Harangi",
            source_type="reservoir",
            full_capacity_mcft=8500.0,
            full_tank_level_ft=None,
            latitude=12.4972,
            longitude=75.9069,
            catchment_area_sqkm=419.0,
            display_order=5,
            is_primary_drinking_source=False,
        ),
        WaterSourceConfig(
            source_code="biligundlu",
            display_name="Biligundlu (CWMA control)",
            source_type="flow_station",
            full_capacity_mcft=None,
            full_tank_level_ft=None,
            latitude=12.05,
            longitude=77.6,
            catchment_area_sqkm=None,
            display_order=6,
            is_primary_drinking_source=False,
        ),
    ),
    source_name_aliases={
        "mettur": "mettur",
        "mettur dam": "mettur",
        "krs": "krs",
        "krishna raja sagara": "krs",
        "krishnarajasagara": "krs",
        "kabini": "kabini",
        "hemavathy": "hemavathy",
        "hemavathi": "hemavathy",
        "harangi": "harangi",
        "biligundlu": "biligundlu",
    },
)
