from .types import (
    Authority,
    CityConfig,
    Coordinates,
    GeoBounds,
    LocalGovernment,
    WaterSourceConfig,
)

MADURAI = CityConfig(
    city_id="madurai",
    display_name="Madurai",
    state_code="TN",
    timezone="Asia/Kolkata",
    center=Coordinates(lat=9.9252, lng=78.1198),
    bbox=GeoBounds(south=9.85, north=10.0, west=78.05, east=78.2),
    primary_authority=Authority(
        code="mmc",
        name="Madurai Municipal Corporation",
        acronym="MMC",
    ),
    local_government=LocalGovernment(
        code="mmc",
        name="Madurai Municipal Corporation",
        acronym="MMC",
        ward_count=100,
    ),
    default_consumption_mld=135.0,
    default_desalination_mld=None,
    water_sources=(
        WaterSourceConfig(
            source_code="vaigai",
            display_name="Vaigai Dam",
            source_type="reservoir",
            full_capacity_mcft=6837.0,
            full_tank_level_ft=71.0,
            latitude=10.0533,
            longitude=77.5897,
            catchment_area_sqkm=2253.0,
            display_order=1,
            is_primary_drinking_source=True,
        ),
        WaterSourceConfig(
            source_code="mullaperiyar",
            display_name="Mullaperiyar (Periyar) Dam",
            source_type="reservoir",
            full_capacity_mcft=15660.0,
            full_tank_level_ft=152.0,
            latitude=9.5394,
            longitude=77.1422,
            catchment_area_sqkm=624.0,
            display_order=2,
            is_primary_drinking_source=True,
        ),
        WaterSourceConfig(
            source_code="sothuparai",
            display_name="Sothuparai Dam",
            source_type="reservoir",
            full_capacity_mcft=1272.0,
            full_tank_level_ft=None,
            latitude=10.07,
            longitude=77.45,
            catchment_area_sqkm=None,
            display_order=3,
            is_primary_drinking_source=False,
        ),
    ),
    source_name_aliases={
        "vaigai": "vaigai",
        "vaigai dam": "vaigai",
        "வைகை": "vaigai",
        "mullaperiyar": "mullaperiyar",
        "mullai periyar": "mullaperiyar",
        "periyar": "mullaperiyar",
        "periyar dam": "mullaperiyar",
        "மூலைப்பெரியார்": "mullaperiyar",
        "sothuparai": "sothuparai",
        "sothuparai dam": "sothuparai",
        "சோத்துப்பாறை": "sothuparai",
    },
)
