from __future__ import annotations

from datetime import date
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[3]
PUBLIC_DIR = REPO_ROOT / "public"
PUBLIC_DATA_DIR = PUBLIC_DIR / "data"
PUBLIC_GEOJSON_DIR = PUBLIC_DIR / "geojson"

PHASE1_TARGETS_PATH = PUBLIC_DATA_DIR / "gee-phase1-water-body-targets.json"
RESERVOIR_CATCHMENTS_PATH = PUBLIC_GEOJSON_DIR / "chennai-reservoir-catchments.geojson"
CURRENT_WATER_BODIES_PATH = PUBLIC_GEOJSON_DIR / "chennai-water-bodies-current.geojson"

PHASE1_RESERVOIRS = (
    "poondi",
    "redhills",
    "chembarambakkam",
    "cholavaram",
)

CHIRPS_DAILY_DATASET = "UCSB-CHG/CHIRPS/DAILY"
CHIRPS_BAND = "precipitation"
CHIRPS_PIXEL_SCALE_METERS = 5566
CHIRPS_START_DATE = date(1981, 1, 1)

DEFAULT_RAIN_WINDOWS = (7, 30, 90)
DEFAULT_BASELINE_YEARS = 20

JRC_MONTHLY_RECURRENCE_DATASET = "JRC/GSW1_4/MonthlyRecurrence"
JRC_MONTHLY_RECURRENCE_BAND = "monthly_recurrence"
JRC_PIXEL_SCALE_METERS = 30

DYNAMIC_WORLD_DATASET = "GOOGLE/DYNAMICWORLD/V1"
DYNAMIC_WORLD_WATER_BAND = "water"
DYNAMIC_WORLD_PIXEL_SCALE_METERS = 10
DEFAULT_WATER_BODY_LOOKBACK_DAYS = 45
DEFAULT_WATER_BODY_MIN_VALID_PCT = 40.0
DEFAULT_PERSISTENCE_PRESENCE_FRACTION = 0.15
DEFAULT_PERSISTENCE_MIN_AREA_HA = 1.0
DEFAULT_BACKFILL_MONTHS_BACK = 24
MAX_OBSERVATION_METADATA_IMAGE_SCANS = 15

SENTINEL2_HARMONIZED_DATASET = "COPERNICUS/S2_HARMONIZED"
SENTINEL2_SR_HARMONIZED_DATASET = "COPERNICUS/S2_SR_HARMONIZED"
SENTINEL2_TRUE_COLOR_BANDS = ("B4", "B3", "B2")
SENTINEL2_PIXEL_SCALE_METERS = 10
# SCL classes to mask: saturated, cloud shadows, cloud medium/high prob, thin cirrus
SENTINEL2_SCL_MASK_VALUES = (1, 3, 8, 9, 10)

SATELLITE_EVIDENCE_BUCKET = "satellite-evidence"
SATELLITE_EVIDENCE_COHORT = "flagship-history"
DEFAULT_SATELLITE_EVIDENCE_MONTHS_BACK = 12
DEFAULT_SATELLITE_EVIDENCE_FRAME_COUNT = 6
DEFAULT_SATELLITE_EVIDENCE_SEARCH_WINDOW_DAYS = 35
DEFAULT_SATELLITE_EVIDENCE_MIN_USABLE_COVERAGE_PCT = 80.0
DEFAULT_SATELLITE_EVIDENCE_MAX_SCENE_CLOUD_PCT = 35.0
DEFAULT_SATELLITE_EVIDENCE_MAX_SCENE_CANDIDATES = 12
SATELLITE_EVIDENCE_THUMB_DIMENSIONS = 900
SATELLITE_EVIDENCE_TRUE_COLOR_FORMAT = "jpg"
SATELLITE_EVIDENCE_OVERLAY_FORMAT = "png"
SATELLITE_EVIDENCE_TRUE_COLOR_MIN = 0
SATELLITE_EVIDENCE_TRUE_COLOR_MAX = (
    3000  # Works for both TOA and SR with gamma correction
)
SATELLITE_EVIDENCE_TRUE_COLOR_GAMMA = 1.2
SATELLITE_EVIDENCE_OVERLAY_PALETTE = ("3b82f6",)
SATELLITE_EVIDENCE_OVERLAY_OPACITY = 0.55

# NDWI water detection (replaces Dynamic World for evidence overlays)
NDWI_GREEN_BAND = "B3"
NDWI_NIR_BAND = "B8"
NDWI_WATER_THRESHOLD = 0.0

FLAGSHIP_HISTORY_COHORT = (
    "osm:25453624",  # Chembarambakkam Lake
    "osm:25394157",  # Red Hills Reservoir
    "osm:25394523",  # Sholavaram Lake
    "osm:24161888",  # Kolavai Lake
    "osm:25391800",  # Ambattur Lake
    "osm:25474612",  # Korattur Lake
    "osm:25474749",  # Retteri Lake
    "osm:1237456198",  # Ayanambakkam Tank
    "osm:30424450",  # Perumbakkam Lake
    "osm:23648233",  # Tiruneermalai Eri
    "osm:1236160012",  # Poonamallee Lake
    "osm:23633592",  # Porur Lake
)
