#!/usr/bin/env python3
"""Generate schemas/nvdm/REFERENCE.md from the schemas, the scope registry and the validator's constants.

Usage: python3 scripts/build_nvdm_reference.py
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))
import nvdm_scopes  # noqa: E402
import validate_nvdm as V  # noqa: E402

OUT = V.SCHEMA_DIR / "REFERENCE.md"
ENVELOPE_DEFS = ("envelope", "scope", "provenance", "source", "projection", "rights_determination")


def cell(text) -> str:
    return str(text).replace("|", "\\|").replace("\n", " ")


def table(head: list[str], rows: list[list]) -> list[str]:
    lines = ["| " + " | ".join(head) + " |", "|" + "---|" * len(head)]
    return lines + ["| " + " | ".join(cell(c) for c in r) + " |" for r in rows] + [""]


def code(values) -> str:
    return ", ".join(f"`{v}`" for v in values) or "-"


def type_of(prop: dict, owner: str, schemas: dict) -> str:
    if "$ref" in prop:
        if "/properties/" not in prop["$ref"]:
            return f"`{prop['$ref'].rsplit('/', 1)[-1]}`"
        return type_of(*V.resolve_ref(prop["$ref"], owner, schemas), schemas)
    if "enum" in prop:
        return "one of " + code(prop["enum"])
    kind = prop.get("type", "any")
    kind = " or ".join(kind) if isinstance(kind, list) else kind
    if kind == "array" and "items" in prop:
        kind += " of " + type_of(prop["items"], owner, schemas)
    limits = [f"{label} {prop[k]}" for k, label in (("minItems", "at least"), ("minLength", "min length")) if k in prop]
    return kind + "".join(f", {x}" for x in limits) + (f", pattern `{prop['pattern']}`" if "pattern" in prop else "")


def fields(defn: dict, owner: str, schemas: dict) -> list[str]:
    required = set(defn.get("required", []))
    rows = [[f"`{k}`", "yes" if k in required else "no", type_of(p, owner, schemas), p.get("description", "")]
            for k, p in defn.get("properties", {}).items()]
    return table(["field", "required", "type", "description"], rows)


def record_keys(schema: dict) -> str:
    """Required keys of each record collection a contract declares."""
    out = []
    for key, prop in schema.get("properties", {}).items():
        items = prop.get("items", {})
        if key == "features":
            key, items = "features[].properties", items.get("properties", {}).get("properties", {})
        if items.get("required"):
            out.append(f"`{key}`: " + ", ".join(items["required"]))
    return "; ".join(out) or "-"


def scope_rows(scopes: dict) -> list[list]:
    rows = []
    for sid, e in sorted(scopes.items(), key=lambda kv: (kv[1]["kind"], kv[0])):
        others = [f"{r['type']} {r['target']}" + (f" ({r['method']})" if r.get("method") else "")
                  for r in e.get("relations", []) if r["type"] != nvdm_scopes.PARENT]
        rows.append([
            f"`{sid}`", e["kind"], e["name"],
            code(nvdm_scopes.related(sid, nvdm_scopes.PARENT, scopes)),
            code(sorted(nvdm_scopes.countries(sid, scopes))),
            ", ".join(f"{r['system']} {r['level']} `{r['code']}`" for r in e.get("refs", [])) or "-",
            "; ".join(others) or "-",
        ])
    return rows


def main() -> None:
    schemas, scopes = V.load_schemas(), V.load_scopes()
    env = schemas["envelope.schema.json"]["$defs"]
    reg = schemas["scopes.schema.json"]["$defs"]
    lines = [
        "# NVDM reference",
        "",
        "Generated by `scripts/build_nvdm_reference.py` from the schemas in this directory, the scope",
        "registry and the constants in `scripts/validate_nvdm.py`. Do not edit by hand: change the",
        "source and regenerate. [RULES.md](RULES.md) explains what each item means.",
        "",
        "## Envelope fields",
        "",
        "Descriptions are the schema's own. A type in backticks names another table in this section.",
        "`date` is a string: " + env["date"]["description"] + f" Pattern: `{env['date']['pattern']}`.",
        "",
    ]
    for name in ENVELOPE_DEFS:
        lines += [f"### `{name}`", ""]
        if env[name].get("description"):
            lines += [env[name]["description"], ""]
        lines += fields(env[name], "envelope.schema.json", schemas)

    lines += ["## Closed vocabularies", ""]
    lines += table(["vocabulary", "values", "defined in"], [
        ["scope kind", code(env["scope"]["properties"]["kind"]["enum"]), "envelope.schema.json"],
        ["water-system kinds (the rest are places)", code(nvdm_scopes.WATER_KINDS), "scripts/nvdm_scopes.py"],
        ["provenance method", code(env["provenance"]["properties"]["method"]["enum"]), "envelope.schema.json"],
        ["source role", code(env["source"]["properties"]["role"]["enum"]), "envelope.schema.json"],
        ["projection method", code(env["projection"]["properties"]["method"]["enum"]), "envelope.schema.json"],
        ["rights determination basis", code(env["rights_determination"]["properties"]["basis"]["enum"]), "envelope.schema.json"],
        ["ref system", code(reg["ref"]["properties"]["system"]["enum"]), "scopes.schema.json"],
        ["ref level", code(reg["ref"]["properties"]["level"]["enum"]), "scopes.schema.json"],
        ["relation type", code(reg["relation"]["properties"]["type"]["enum"]), "scopes.schema.json"],
        ["relation method", code(reg["relation"]["properties"]["method"]["enum"]), "scopes.schema.json"],
    ])

    lines += ["## Scope registry entry", ""]
    for name in ("entry", "ref", "relation"):
        lines += [f"### `{name}`", ""] + fields(reg[name], "scopes.schema.json", schemas)

    lines += [f"## Registered scopes ({len(scopes)})", "",
              "Country is derived from the relations, never stored.", ""]
    lines += table(["id", "kind", "name", "administrative parent", "country", "external identities", "other relations"],
                   scope_rows(scopes))

    lines += ["## Payload contracts", "",
              "A dataset listed here can reach L3. Every contract also requires the envelope.", ""]
    lines += table(["dataset", "schema", "required top-level keys", "required keys per record"], [
        [f"`{ds}`", f"[{f}]({f})", code(schemas[f].get("required", [])), record_keys(schemas[f])]
        for ds, f in V.CONTRACTS.items()])

    lines += ["## Claim datasets", "",
              "Every record in the named collection must carry at least one of the listed keys.", ""]
    lines += table(["dataset", "record collection", "accepted per-record source keys"], [
        [f"`{ds}`", f"`{coll}`", code(keys)] for ds, (coll, keys) in V.CLAIM_DATASETS.items()])

    lines += [
        "## Top-level keys a contracted artifact may carry", "",
        f"- Envelope keys: {code(sorted(V.ENVELOPE_KEYS))}",
        f"- GeoJSON members: {code(sorted(V.GEOJSON_MEMBERS))}",
        "- The keys its contract declares.",
        f"- Grandfathered legacy keys (closed list): {code(sorted(V.LEGACY_GRANDFATHERED))}",
        f"- Grandfathered underscore keys (closed list): {code(sorted(V.LEGACY_UNDERSCORE))}",
        "",
        "## JSON Schema keywords the validator supports", "",
        "Enforced keywords and pure annotations. A schema that uses any other keyword fails the selftest.", "",
        code(sorted(V.SCHEMA_KEYWORDS)), "",
    ]

    lines += ["## Current conformance levels", "",
              "The level of every artifact, with counts by family, is in the conformance report:",
              "[docs/architecture/nvdm-conformance.md](../../docs/architecture/nvdm-conformance.md).", ""]

    OUT.write_text("\n".join(lines))
    print(f"{len(scopes)} scopes, {len(V.CONTRACTS)} contracts -> {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
