/**
 * Reverse-geocode each unnamed Madurai water-body polygon via OSM
 * Nominatim and write a friendly "{Locality} tank" / "{Locality}
 * pond" name back into the geojson, so the map's tooltips and the
 * detail panel stop showing "<unnamed water>".
 *
 * Polite to Nominatim:
 *   - 1.1 s sleep between requests
 *   - Custom User-Agent
 *   - Cache results to scripts/_cache-madurai-wb-names.json so reruns
 *     don't re-query already-resolved bodies. Delete the cache file
 *     to force a full re-fetch.
 *
 * Run:
 *   npx tsx scripts/name-madurai-water-bodies.ts
 *   npx tsx scripts/name-madurai-water-bodies.ts --limit 50  (debug)
 *
 * Inputs:
 *   public/geojson/madurai-water-bodies-current.geojson
 *
 * Outputs:
 *   - same geojson rewritten with derived names (in-place)
 *   - scripts/_cache-madurai-wb-names.json  (persistent cache,
 *     gitignored)
 */

import { readFileSync, writeFileSync, existsSync } from "fs";
import { resolve } from "path";

const root = process.cwd();

interface Polygon {
  type: "Polygon" | "MultiPolygon";
  coordinates: number[][][] | number[][][][];
}

interface Feature {
  type: "Feature";
  properties: {
    osm_id?: number;
    osm_type?: string;
    name?: string;
    name_ta?: string;
    water_type?: string;
    area_ha?: number;
    /** True if name was generated by this script (so we can re-derive on rerun). */
    name_derived?: boolean;
  };
  geometry: Polygon;
}

interface FeatureCollection {
  type: "FeatureCollection";
  features: Feature[];
}

interface NominatimAddress {
  village?: string;
  hamlet?: string;
  suburb?: string;
  neighbourhood?: string;
  town?: string;
  city?: string;
  city_district?: string;
  state_district?: string;
  county?: string;
}

interface NominatimReverse {
  display_name?: string;
  address?: NominatimAddress;
}

function polygonCentroid(coords: number[][][]): [number, number] {
  // Outer ring centroid, [lng, lat]
  const ring = coords[0];
  let lat = 0,
    lng = 0;
  for (const [x, y] of ring) {
    lng += x;
    lat += y;
  }
  return [lng / ring.length, lat / ring.length];
}

function multipolygonCentroid(coords: number[][][][]): [number, number] {
  // Use the largest ring's centroid as a proxy
  let best: [number, number] | null = null;
  let bestSize = -1;
  for (const poly of coords) {
    const ring = poly[0];
    if (ring.length > bestSize) {
      best = polygonCentroid(poly);
      bestSize = ring.length;
    }
  }
  return best ?? [0, 0];
}

function centroidOf(geom: Polygon): [number, number] {
  return geom.type === "Polygon"
    ? polygonCentroid(geom.coordinates as number[][][])
    : multipolygonCentroid(geom.coordinates as number[][][][]);
}

async function reverseGeocode(lat: number, lng: number): Promise<NominatimReverse | null> {
  // zoom=14 gives village / suburb resolution
  const url = `https://nominatim.openstreetmap.org/reverse?format=json&lat=${lat}&lon=${lng}&zoom=14&addressdetails=1`;
  try {
    const r = await fetch(url, {
      headers: { "User-Agent": "neer-vazhvu-bot/1.0 (research)" },
    });
    if (!r.ok) return null;
    return (await r.json()) as NominatimReverse;
  } catch {
    return null;
  }
}

function pickLocality(addr: NominatimAddress | undefined): string | null {
  if (!addr) return null;
  // Preference order: village > hamlet > suburb > neighbourhood > town
  return (
    addr.village ??
    addr.hamlet ??
    addr.suburb ??
    addr.neighbourhood ??
    addr.town ??
    addr.city_district ??
    addr.city ??
    null
  );
}

function nameFromLocality(locality: string, waterType: string | undefined): string {
  // OSM water_type values include "water", "reservoir", "pond", "river"
  const type = (waterType ?? "").toLowerCase();
  if (type === "river") return `River near ${locality}`;
  if (type === "reservoir") return `Reservoir near ${locality}`;
  if (type === "pond") return `Pond near ${locality}`;
  // Default - "tank" is the South Indian default for irrigation water bodies
  return `Tank near ${locality}`;
}

function sleep(ms: number): Promise<void> {
  return new Promise((res) => setTimeout(res, ms));
}

interface CacheEntry {
  locality: string | null;
  fetched_at: string;
}

async function main() {
  const args = process.argv.slice(2);
  const limitFlag = args.indexOf("--limit");
  const limit = limitFlag >= 0 ? parseInt(args[limitFlag + 1] ?? "0", 10) : 0;

  const geoPath = resolve(root, "public/geojson/madurai-water-bodies-current.geojson");
  const cachePath = resolve(root, "scripts/_cache-madurai-wb-names.json");
  const geo = JSON.parse(readFileSync(geoPath, "utf-8")) as FeatureCollection;

  // Load cache. Key is osm_id (stable across runs).
  const cache: Record<string, CacheEntry> = existsSync(cachePath)
    ? (JSON.parse(readFileSync(cachePath, "utf-8")) as Record<string, CacheEntry>)
    : {};

  // Pick targets: features that don't already have a hand-curated name
  // (or have only a derived name that we want to refresh).
  const targets = geo.features.filter((f) => {
    const existing = (f.properties.name ?? "").trim();
    if (!existing) return true; // unnamed
    if (f.properties.name_derived) return true; // we generated this previously - skip if cached
    return false;
  });
  const cappedTargets = limit > 0 ? targets.slice(0, limit) : targets;

  console.log(`Total features: ${geo.features.length}`);
  console.log(`Unnamed / derived-named targets: ${targets.length}`);
  if (limit > 0) console.log(`Processing first ${limit} (--limit)`);
  console.log(`Cache hits available: ${Object.keys(cache).length}`);
  console.log("");

  let resolved = 0;
  let cacheHits = 0;
  let unresolved = 0;

  for (let i = 0; i < cappedTargets.length; i++) {
    const f = cappedTargets[i];
    const key = String(f.properties.osm_id ?? `${f.properties.osm_type}-${i}`);

    let entry: CacheEntry | undefined = cache[key];
    if (!entry) {
      const [lng, lat] = centroidOf(f.geometry);
      const result = await reverseGeocode(lat, lng);
      entry = {
        locality: pickLocality(result?.address),
        fetched_at: new Date().toISOString(),
      };
      cache[key] = entry;
      // Write cache after every fetch so a crash mid-run preserves work.
      writeFileSync(cachePath, JSON.stringify(cache, null, 2));
      await sleep(1100); // be polite
    } else {
      cacheHits++;
    }

    if (entry.locality) {
      // Stash the bare locality on the feature - the dedup pass below
      // turns it into a final name that adds an area qualifier when
      // multiple bodies share the same locality + water_type.
      (f.properties as { _locality?: string })._locality = entry.locality;
      resolved++;
    } else {
      unresolved++;
    }

    if ((i + 1) % 25 === 0) {
      console.log(
        `  ${i + 1}/${cappedTargets.length}  resolved=${resolved}  cached=${cacheHits}  unresolved=${unresolved}`,
      );
    }
  }

  // Dedup pass: when multiple bodies share the same (locality,
  // water_type) - common on big OSM-tagged industrial reservoir
  // clusters - append the body's area so each marker is identifiable.
  const groupCounts = new Map<string, number>();
  for (const f of geo.features) {
    const loc = (f.properties as { _locality?: string })._locality;
    if (!loc) continue;
    const key = `${loc.toLowerCase()}|${(f.properties.water_type ?? "tank").toLowerCase()}`;
    groupCounts.set(key, (groupCounts.get(key) ?? 0) + 1);
  }
  for (const f of geo.features) {
    const loc = (f.properties as { _locality?: string })._locality;
    if (!loc) continue;
    const key = `${loc.toLowerCase()}|${(f.properties.water_type ?? "tank").toLowerCase()}`;
    const baseName = nameFromLocality(loc, f.properties.water_type);
    if ((groupCounts.get(key) ?? 0) > 1 && f.properties.area_ha != null) {
      f.properties.name = `${baseName} (${f.properties.area_ha.toFixed(1)} ha)`;
    } else {
      f.properties.name = baseName;
    }
    f.properties.name_derived = true;
    delete (f.properties as { _locality?: string })._locality;
  }

  // Write geojson back
  writeFileSync(geoPath, JSON.stringify(geo, null, 2));
  console.log("");
  console.log(`Done.`);
  console.log(`  resolved (named):    ${resolved}`);
  console.log(`  cache hits:          ${cacheHits}`);
  console.log(`  unresolved:          ${unresolved}`);
  console.log(`  total geojson features: ${geo.features.length}`);
  const namedNow = geo.features.filter((f) => (f.properties.name ?? "").trim()).length;
  console.log(`  named now: ${namedNow} (${((namedNow / geo.features.length) * 100).toFixed(1)}%)`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
