/** Copy for the sections of Bengaluru's tanker page (en/ta/kn): the expanded
 *  tanker context, and the IISc stress-ward map (also a /groundwater view). */
export const TANKER_CONTEXT_COPY = {
  section: {
    structural_anchor: { en: "Structural picture: where Bengaluru's water actually comes from", ta: "கட்டமைப்புப் படம்: பெங்களூரு நீர் உண்மையில் எங்கிருந்து வருகிறது", kn: "ಕಟ್ಟಡ ಚಿತ್ರ: ಬೆಂಗಳೂರಿನ ನೀರು ವಾಸ್ತವವಾಗಿ ಎಲ್ಲಿಂದ ಬರುತ್ತದೆ" },
    structural_body: { en: "Bengaluru's 14M residents consume ~2,830 MLD - the gap between BWSSB's piped supply and household demand is what the tanker market fills.", ta: "பெங்களூரின் 1.4 கோடி குடியிருப்பாளர்கள் ~2,830 MLD நுகர்கிறார்கள் - BWSSB-ன் குழாய் வழங்கல் மற்றும் வீட்டு தேவை இடைவெளியே டேங்கர் சந்தை நிரப்புகிறது.", kn: "ಬೆಂಗಳೂರಿನ 1.4 ಕೋಟಿ ನಿವಾಸಿಗಳು ~2,830 MLD ಬಳಸುತ್ತಾರೆ - BWSSB ಯ ಪೈಪ್ ಪೂರೈಕೆ ಮತ್ತು ಮನೆಯ ಬೇಡಿಕೆ ನಡುವಿನ ಅಂತರವನ್ನು ಟ್ಯಾಂಕರ್ ಮಾರುಕಟ್ಟೆ ತುಂಬುತ್ತದೆ." },
    crisis_headline: { en: "How the March 2024 crisis unfolded", ta: "மார்ச் 2024 நெருக்கடி எவ்வாறு வெளிப்பட்டது", kn: "ಮಾರ್ಚ್ 2024 ರ ಬಿಕ್ಕಟ್ಟು ಹೇಗೆ ತೆರೆದುಕೊಂಡಿತು" },
    crisis_subtitle: { en: "A Cauvery-deficit summer + collapsed monsoon recharge took private tanker rates from ~Rs 800 to ~Rs 2,850 in 6 weeks. Government scrambled to register the informal fleet and impose price ceilings.", ta: "காவிரி-பற்றாக்குறை கோடை + சரிந்த பருவமழை நிரப்புதல் தனியார் டேங்கர் கட்டணங்களை ~ரூ 800-ல் இருந்து ~ரூ 2,850-க்கு 6 வாரங்களில் கொண்டுசென்றது. அரசு அதிகாரப்பூர்வமற்ற கப்பலை பதிவு செய்ய மற்றும் விலை உச்சவரம்புகளை விதிக்க முயன்றது.", kn: "ಕಾವೇರಿ-ಕೊರತೆ ಬೇಸಿಗೆ + ಕುಸಿದ ಮುಂಗಾರು ಮರುಪೂರಣ ಖಾಸಗಿ ಟ್ಯಾಂಕರ್ ದರಗಳನ್ನು 6 ವಾರಗಳಲ್ಲಿ ~ರೂ 800 ರಿಂದ ~ರೂ 2,850 ಗೆ ಕೊಂಡೊಯ್ಯಿತು. ಸರ್ಕಾರ ಅನೌಪಚಾರಿಕ ಫ್ಲೀಟ್ ಅನ್ನು ನೋಂದಾಯಿಸಲು ಮತ್ತು ಬೆಲೆ ಮಿತಿಗಳನ್ನು ವಿಧಿಸಲು ಧಾವಿಸಿತು." },
    rate_gap_headline: { en: "Official vs informal pricing: a 4-tier rate gap", ta: "அதிகாரப்பூர்வ vs அதிகாரப்பூர்வமற்ற விலை: 4-அடுக்கு கட்டண இடைவெளி", kn: "ಅಧಿಕೃತ vs ಅನೌಪಚಾರಿಕ ಬೆಲೆ: 4-ಹಂತ ದರ ಅಂತರ" },
    rate_gap_subtitle: { en: "Bengaluru's tanker market runs on 4 distinct rate tiers: BWSSB's official Kaveriwheels app, the BBMP-mandated crisis-cap, the registered informal fleet, and the unregistered crisis-peak. The spread is the structural rent the informal market captures.", ta: "பெங்களூரின் டேங்கர் சந்தை 4 தனிப்பட்ட கட்டண அடுக்குகளில் இயங்குகிறது: BWSSB-ன் அதிகாரப்பூர்வ Kaveriwheels செயலி, BBMP-உத்தரவான நெருக்கடி-உச்சவரம்பு, பதிவு செய்யப்பட்ட அதிகாரப்பூர்வமற்ற கப்பல், மற்றும் பதிவு செய்யப்படாத நெருக்கடி-உச்சம்.", kn: "ಬೆಂಗಳೂರಿನ ಟ್ಯಾಂಕರ್ ಮಾರುಕಟ್ಟೆ 4 ವಿಭಿನ್ನ ದರ ಹಂತಗಳಲ್ಲಿ ಚಲಿಸುತ್ತದೆ: BWSSB ಯ ಅಧಿಕೃತ Kaveriwheels ಆ್ಯಪ್, BBMP-ಆದೇಶಿತ ಬಿಕ್ಕಟ್ಟು-ಮಿತಿ, ನೋಂದಾಯಿತ ಅನೌಪಚಾರಿಕ ಫ್ಲೀಟ್, ಮತ್ತು ನೋಂದಣಿರಹಿತ ಬಿಕ್ಕಟ್ಟು-ಶಿಖರ. ವ್ಯತ್ಯಾಸವೇ ಅನೌಪಚಾರಿಕ ಮಾರುಕಟ್ಟೆ ಸೆರೆಹಿಡಿಯುವ ಕಟ್ಟಡ ಬಾಡಿಗೆ." },
    extraction_headline: { en: "Named extraction sites + regulatory gap", ta: "பெயரிடப்பட்ட எடுப்பு இடங்கள் + ஒழுங்குமுறை இடைவெளி", kn: "ಹೆಸರಿಸಲಾದ ಎತ್ತುವ ಸ್ಥಳಗಳು + ನಿಯಂತ್ರಕ ಅಂತರ" },
    extraction_subtitle: { en: "Where the tanker fleet actually pulls its water from - five typed sites compiled from press + IISc + KSPCB sources.", ta: "டேங்கர் கப்பல் உண்மையில் நீர் எடுக்கும் இடம் - பத்திரிக்கை + IISc + KSPCB ஆதாரங்களில் இருந்து தொகுக்கப்பட்ட ஐந்து வகை இடங்கள்.", kn: "ಟ್ಯಾಂಕರ್ ಫ್ಲೀಟ್ ವಾಸ್ತವವಾಗಿ ತನ್ನ ನೀರನ್ನು ಎಲ್ಲಿಂದ ಎಳೆಯುತ್ತದೆ - ಪತ್ರಿಕೆ + IISc + KSPCB ಮೂಲಗಳಿಂದ ಸಂಗ್ರಹಿಸಿದ ಐದು ಪ್ರಕಾರದ ಸ್ಥಳಗಳು." },
    extraction_gap: { en: "Regulatory gap: BWSSB licenses tanker operators but BBMP/BWSSB do NOT track per-vehicle source of water sold. Operators are free to fill anywhere - including from over-extracted private borewells - then resell as 'tanker water' without provenance labeling.", ta: "ஒழுங்குமுறை இடைவெளி: BWSSB டேங்கர் இயக்குநர்களுக்கு உரிமம் வழங்குகிறது ஆனால் BBMP/BWSSB ஒரு வாகனத்துக்கு விற்கப்படும் நீரின் மூலத்தை கண்காணிக்காது.", kn: "ನಿಯಂತ್ರಕ ಅಂತರ: BWSSB ಟ್ಯಾಂಕರ್ ಆಪರೇಟರ್‌ಗಳಿಗೆ ಲೈಸೆನ್ಸ್ ನೀಡುತ್ತದೆ ಆದರೆ BBMP/BWSSB ಪ್ರತಿ-ವಾಹನ ಮಾರಲ್ಪಡುವ ನೀರಿನ ಮೂಲವನ್ನು ಮೇಲ್ವಿಚಾರಣೆ ಮಾಡುವುದಿಲ್ಲ." },
    corridors_headline: { en: "Dependency corridors: where tankers fill the gap hardest", ta: "சார்பு வழித்தடங்கள்: டேங்கர்கள் கடினமாக இடைவெளியை நிரப்பும் இடம்", kn: "ಅವಲಂಬನೆ ಕಾರಿಡಾರ್‌ಗಳು: ಟ್ಯಾಂಕರ್‌ಗಳು ಕಷ್ಟವಾಗಿ ಅಂತರವನ್ನು ತುಂಬುವಲ್ಲಿ" },
    corridors_subtitle: { en: "Cross-referencing the highest informal-rate corridors (Rs/kL) with the worst-served wards by piped LPCD reveals the spatial dependency pattern.", ta: "அதிகபட்ச அதிகாரப்பூர்வமற்ற-கட்டண வழித்தடங்களை (ரூ/kL) குழாய் LPCD-ஆல் மோசமாக சேவை செய்யப்பட்ட வார்டுகளுடன் குறுக்கு-குறிப்பு செய்வது இடவியல் சார்பு முறையை வெளிப்படுத்துகிறது.", kn: "ಪೈಪ್ LPCD ಯಿಂದ ಕೆಟ್ಟದಾಗಿ ಸೇವೆ ಪಡೆದ ವಾರ್ಡ್‌ಗಳೊಂದಿಗೆ ಅತಿ ಹೆಚ್ಚಿನ ಅನೌಪಚಾರಿಕ-ದರ ಕಾರಿಡಾರ್‌ಗಳನ್ನು (ರೂ/kL) ಅಡ್ಡ-ಉಲ್ಲೇಖಿಸುವುದು ಪ್ರಾದೇಶಿಕ ಅವಲಂಬನೆ ಮಾದರಿಯನ್ನು ಬಹಿರಂಗಪಡಿಸುತ್ತದೆ." },
  },
  error: { en: "Could not load tanker context. The page falls back to the OpenCity longitudinal survey above.", ta: "டேங்கர் சூழலை ஏற்ற முடியவில்லை.", kn: "ಟ್ಯಾಂಕರ್ ಸಂದರ್ಭವನ್ನು ಲೋಡ್ ಮಾಡಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ. ಪುಟ ಮೇಲಿನ OpenCity ಸಮೀಕ್ಷೆಗೆ ಹಿಂತಿರುಗುತ್ತದೆ." },
  structural_footer: { en: "Numbers from {source}. Sums larger than 2,830 MLD because BWSSB also serves bulk industrial / institutional users outside the household total.", ta: "எண்கள் {source}-ல் இருந்து. மொத்தம் 2,830 MLD-ஐ விட பெரியது ஏனெனில் BWSSB வீட்டு மொத்தத்தைத் தாண்டி பெரிய தொழில்துறை / நிறுவன பயனர்களுக்கும் சேவை செய்கிறது.", kn: "ಸಂಖ್ಯೆಗಳು {source} ರಿಂದ. ಮೊತ್ತಗಳು 2,830 MLD ಗಿಂತ ಹೆಚ್ಚು ಏಕೆಂದರೆ BWSSB ಮನೆಯ ಒಟ್ಟು ಮೀರಿ ದೊಡ್ಡ ಕೈಗಾರಿಕಾ / ಸಂಸ್ಥಾಗತ ಬಳಕೆದಾರರಿಗೂ ಸೇವೆ ಸಲ್ಲಿಸುತ್ತದೆ." },
  fleet: { en: "fleet ~{n}", ta: "கப்பல் ~{n}", kn: "ಫ್ಲೀಟ್ ~{n}" },
  rates_heading: { en: "Highest informal tanker rates (Rs / kL, 2025)", ta: "அதிகபட்ச அதிகாரப்பூர்வமற்ற டேங்கர் கட்டணங்கள் (ரூ / kL, 2025)", kn: "ಅತಿ ಹೆಚ್ಚಿನ ಅನೌಪಚಾರಿಕ ಟ್ಯಾಂಕರ್ ದರಗಳು (ರೂ / kL, 2025)" },
  worst_served: { en: "Worst-served by piped supply (Cauvery LPCD)", ta: "குழாய் வழங்கலில் மோசமாக சேவை செய்யப்பட்டவர்கள் (காவிரி LPCD)", kn: "ಪೈಪ್ ಪೂರೈಕೆಯಿಂದ ಅತ್ಯಂತ ಕಡಿಮೆ ಸೇವೆ (ಕಾವೇರಿ LPCD)" },
  mohua_note: { en: "MoHUA Service Level Benchmark target: 135 LPCD.", ta: "MoHUA சேவை அளவு குறிக்கோள்: 135 LPCD.", kn: "MoHUA ಸೇವಾ ಮಟ್ಟ ಗುರಿ: 135 LPCD." },
  stress_footer: { en: "IISc Groundwater Outlook flags {count} BBMP wards as critically over-extracted. Mapping that 65-ward list onto a choropleth on this page is a Tier-1 follow-up (IISc PDF parse required - see data gaps below).", ta: "IISc நிலத்தடி நீர் கண்காணிப்பு {count} BBMP வார்டுகளை மிகவும் அதிகமாக எடுக்கப்பட்டவை என அடையாளம் காட்டுகிறது.", kn: "IISc ಅಂತರ್ಜಲ ಔಟ್‌ಲುಕ್ {count} BBMP ವಾರ್ಡ್‌ಗಳನ್ನು ಗಂಭೀರವಾಗಿ ಅತಿ-ಎತ್ತಲ್ಪಟ್ಟ ಎಂದು ಗುರುತಿಸಿದೆ. 65-ವಾರ್ಡ್ ಪಟ್ಟಿಯನ್ನು ಈ ಪುಟದಲ್ಲಿ ಚೋರೋಪ್ಲೆತ್‌ಗೆ ನಕ್ಷೆ ಮಾಡುವುದು Tier-1 ಅನುಸರಣೆ." },
  site_type: {
    illegal_lake_abstraction: { en: "Illegal lake abstraction", ta: "சட்டவிரோத ஏரி எடுப்பு", kn: "ಅಕ್ರಮ ಕೆರೆ ಎತ್ತುವಿಕೆ" },
    illegal_lake_buffer_borewell: { en: "Illegal lake-buffer borewell", ta: "சட்டவிரோத ஏரி-தாங்கல் ஆழ்துளை", kn: "ಅಕ್ರಮ ಕೆರೆ-ಬಫರ್ ಬೋರ್‌ವೆಲ್" },
    industrial_borewell: { en: "Industrial borewell (diverted)", ta: "தொழில்துறை ஆழ்துளை (திருப்பப்பட்டது)", kn: "ಕೈಗಾರಿಕಾ ಬೋರ್‌ವೆಲ್ (ಬದಲಿಸಲಾಗಿದೆ)" },
    over_extracted_private_borewell: { en: "Over-extracted private borewell", ta: "அதிகமாக எடுக்கப்பட்ட தனியார் ஆழ்துளை", kn: "ಅತಿ-ಎತ್ತಲ್ಪಟ್ಟ ಖಾಸಗಿ ಬೋರ್‌ವೆಲ್" },
    treated_wastewater: { en: "Treated wastewater (legitimate)", ta: "சுத்திகரிக்கப்பட்ட கழிவு நீர் (சட்டபூர்வ)", kn: "ಸಂಸ್ಕರಿಸಿದ ತ್ಯಾಜ್ಯ ನೀರು (ಕಾನೂನುಬದ್ಧ)" },
  },
};

export const IISC_MAP_COPY = {
  error: { en: "Could not load IISc stress-ward dataset.", ta: "IISc அழுத்த-வார்டு தரவை ஏற்ற முடியவில்லை.", kn: "IISc ಒತ್ತಡ-ವಾರ್ಡ್ ದತ್ತಾಂಶವನ್ನು ಲೋಡ್ ಮಾಡಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ." },
  heading: { en: "IISc's 80 critically-stressed BBMP wards", ta: "IISc-ன் 80 மிக-அழுத்தமான BBMP வார்டுகள்", kn: "IISc ಯ 80 ಗಂಭೀರವಾಗಿ-ಒತ್ತಡದ BBMP ವಾರ್ಡ್‌ಗಳು" },
  intro: { en: "From IISc's Groundwater Outlook of Bengaluru City - Interim Report II (submitted {date}, projecting {target}). Table 1 of the report lists 80 critical BBMP wards (legacy 198-ward grid) plus 110 peripheral villages. The April-2025 IISc summary that media coverage cites (\"65 wards\") is a later narrower revision; the structural 80-ward list below is the spatial baseline.", ta: "IISc-ன் பெங்களூரு நகரின் நிலத்தடி நீர் கண்காணிப்பு - இடைக்கால அறிக்கை II ({date} சமர்ப்பிக்கப்பட்டது, {target} திட்டமிடுகிறது).", kn: "IISc ಯ ಬೆಂಗಳೂರು ನಗರ ಅಂತರ್ಜಲ ಔಟ್‌ಲುಕ್ - ಮಧ್ಯಂತರ ವರದಿ II ({date} ಸಲ್ಲಿಸಲಾಗಿದೆ, {target} ಪ್ರಕ್ಷೇಪಿಸುತ್ತಿದೆ). ವರದಿಯ ಟೇಬಲ್ 1 80 ನಿರ್ಣಾಯಕ BBMP ವಾರ್ಡ್‌ಗಳನ್ನು ಮತ್ತು 110 ಬಾಹ್ಯ ಗ್ರಾಮಗಳನ್ನು ಪಟ್ಟಿ ಮಾಡುತ್ತದೆ." },
  predicted: { en: "Predicted April-2025 water-level drops from December 2024 baseline: Core Area 5 m - CMC Area 10-15 m - 110 surrounding villages 20-25 m.", ta: "டிசம்பர் 2024 அடிப்படையில் இருந்து ஏப்ரல்-2025 கணிக்கப்பட்ட நீர்-நிலை வீழ்ச்சிகள்: முக்கிய பகுதி 5 மீ - CMC பகுதி 10-15 மீ - 110 சுற்றியுள்ள கிராமங்கள் 20-25 மீ.", kn: "ಡಿಸೆಂಬರ್ 2024 ಆಧಾರದಿಂದ ಏಪ್ರಿಲ್-2025 ಪ್ರಕ್ಷೇಪಿತ ನೀರಿನ-ಮಟ್ಟ ಇಳಿತಗಳು: ಕೋರ್ ಪ್ರದೇಶ 5 ಮೀ - CMC ಪ್ರದೇಶ 10-15 ಮೀ - 110 ಸುತ್ತಲಿನ ಗ್ರಾಮಗಳು 20-25 ಮೀ." },
  legend_title: { en: "Legend", ta: "வரைபட விளக்கம்", kn: "ದಂತಕಥೆ" },
  legend: {
    two_plus: { en: "GBA ward with 2+ stress centroids", ta: "2+ அழுத்த மையங்கள் கொண்ட GBA வார்டு", kn: "2+ ಒತ್ತಡ ಕೇಂದ್ರಗಳಿರುವ GBA ವಾರ್ಡ್" },
    one: { en: "GBA ward with 1 stress centroid", ta: "1 அழுத்த மையம் கொண்ட GBA வார்டு", kn: "1 ಒತ್ತಡ ಕೇಂದ್ರವಿರುವ GBA ವಾರ್ಡ್" },
    hover_name: { en: "GBA ward (hover for name)", ta: "GBA வார்டு (பெயருக்கு நிறுத்தவும்)", kn: "GBA ವಾರ್ಡ್ (ಹೆಸರಿಗೆ ಹೋವರ್ ಮಾಡಿ)" },
    bbmp_centroid: { en: "BBMP stress centroid (hover for ward)", ta: "BBMP அழுத்த மையம் (வார்டுக்கு நிறுத்தவும்)", kn: "BBMP ಒತ್ತಡ ಕೇಂದ್ರ (ವಾರ್ಡ್‌ಗೆ ಹೋವರ್ ಮಾಡಿ)" },
  },
  group_heading: { en: "Grouped by GBA City Corporation", ta: "GBA நகர மாநகராட்சியால் தொகுக்கப்பட்டது", kn: "GBA ನಗರ ನಿಗಮದಿಂದ ಗುಂಪು ಮಾಡಲಾಗಿದೆ" },
};
